[build]
  command = "pip install -r requirements.txt && python3 freeze.py"
  publish = "build"

# Serve extensionless routes by rewriting
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.processing.html]
  pretty_urls = true

